{application,dtm_redis,
             [{description,"Distributed Transaction Redis"},
              {vsn,"0.3"},
              {registered,[]},
              {applications,[kernel,stdlib]},
              {mod,{dtm_redis_app,[]}},
              {env,[]},
              {modules,[acceptance,binlog,bucket,dtm_redis,hash,key_meta,
                        redis_protocol,redis_store,server,session,
                        txn_monitor]}]}.
